repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.2
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.9.6
  hooks:
    - id: uv-export
      args: [--no-hashes -o requirements-dev.txt]
    - id: uv-export
      args: [--extra production --no-hashes -o requirements-prod.txt]