# Generated by Django 3.0.5 on 2020-05-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spexflix', '0004_auto_20200424_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['-year'], 'verbose_name': 'Uppsättning', 'verbose_name_plural': 'Uppsättningar'},
        ),
        migrations.AddField(
            model_name='production',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020, verbose_name='År'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='production',
            name='short_name',
            field=models.CharField(help_text='T.ex Spex-19, men kan också vara något annat som identifierar en speciell uppsättning (t.ex SM-17 eller Jubel-35)', max_length=10, verbose_name='Kortnamn'),
        ),
    ]
