# Generated by Django 3.0.6 on 2020-06-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batadasen', '0003_auto_20200613_0208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationactivity',
            options={'ordering': ['person', 'group'], 'verbose_name': 'föreningsuppdrag', 'verbose_name_plural': 'föreningsuppdrag'},
        ),
        migrations.AlterModelOptions(
            name='associationgroup',
            options={'ordering': ['group_type', 'year'], 'verbose_name': 'föreningsgrupp', 'verbose_name_plural': 'föreningsgrupp'},
        ),
        migrations.AlterModelOptions(
            name='associationgrouptype',
            options={'ordering': ['short_name'], 'verbose_name': 'föreningsgrupptyp', 'verbose_name_plural': 'föreningsgrupptyper'},
        ),
        migrations.AlterModelOptions(
            name='associationmembership',
            options={'ordering': ['person', 'year'], 'verbose_name': 'föreningsmedlemskap', 'verbose_name_plural': 'föreningsmedlemskap'},
        ),
        migrations.AlterModelOptions(
            name='associationyear',
            options={'ordering': ['end_year'], 'verbose_name': 'verksamhetsår', 'verbose_name_plural': 'verksamhetsår'},
        ),
        migrations.AlterModelOptions(
            name='emaillist',
            options={'ordering': ['alias'], 'verbose_name': 'maillista', 'verbose_name_plural': 'maillistor'},
        ),
        migrations.AlterModelOptions(
            name='extraemail',
            options={'ordering': ['person'], 'verbose_name': 'extra mailadress', 'verbose_name_plural': 'extra mailadresser'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['member_number'], 'verbose_name': 'person', 'verbose_name_plural': 'personer'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['number'], 'verbose_name': 'uppsättning', 'verbose_name_plural': 'uppsättningar'},
        ),
        migrations.AlterModelOptions(
            name='productiongroup',
            options={'ordering': ['group_type', 'production'], 'verbose_name': 'uppsättningsgrupp', 'verbose_name_plural': 'uppsättningsgrupper'},
        ),
        migrations.AlterModelOptions(
            name='productiongrouptype',
            options={'ordering': ['short_name'], 'verbose_name': 'uppsättningsgrupptyp', 'verbose_name_plural': 'uppsättningsgrupptyper'},
        ),
        migrations.AlterModelOptions(
            name='productionmembership',
            options={'ordering': ['person', 'group__production'], 'verbose_name': 'uppsättningsmedlemskap', 'verbose_name_plural': 'uppsättningsmedlemskap'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name'], 'verbose_name': 'titel', 'verbose_name_plural': 'titlar'},
        ),
    ]
