# Generated by Django 3.0.7 on 2020-07-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batadasen", "0009_productiongrouptype_exclude_from_production_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillist",
            name="is_internal",
            field=models.BooleanField(
                default=True,
                help_text="Ska endast spexare få skicka till denna lista?",
                verbose_name="intern lista",
            ),
        ),
    ]
