# Generated by Django 3.0.7 on 2020-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batadasen', '0010_emaillist_is_internal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='honorary_member',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lifetime_member',
        ),
        migrations.AddField(
            model_name='associationmembership',
            name='membership_type',
            field=models.CharField(choices=[('STD', 'Vanlig medlem'), ('HON', 'Hedersmedlem'), ('LIF', 'Livstidsmedlem')], default='STD', help_text='För vanligt medlemskap, lägg till nytt medlemskap för varje år.För livstidsmedlemskap och hedersmedlemskap, lägg in det året de blev livstid- eller hedersmedlemmar.', max_length=3, verbose_name='medlemskapstyp'),
        ),
        migrations.AlterField(
            model_name='emaillist',
            name='productions',
            field=models.ManyToManyField(blank=True, help_text='Denna lista kommer skicka mail till följande HELA uppsättningar, förutom i de fall då listans namn slutar med "gruppledare".', related_name='email_lists', to='batadasen.Production', verbose_name='hela uppsättningar'),
        ),
        migrations.AlterUniqueTogether(
            name='associationmembership',
            unique_together={('person', 'year', 'membership_type')},
        ),
    ]
