# Generated by Django 4.1.4 on 2024-10-01 11:22

import batadasen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batadasen', '0014_person_email_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['member_number'], 'permissions': [('view_private_info', 'Kan se all personinfo oavsett personens inställningar'), ('view_performances', 'Kan se loggade föreställnigar')], 'verbose_name': 'person', 'verbose_name_plural': 'personer'},
        ),
        migrations.AlterField(
            model_name='emaillist',
            name='alias',
            field=batadasen.models.EmailField(help_text='Namnet på listan, det som står framför @', max_length=50, primary_key=True, serialize=False, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='person',
            name='privacy_setting',
            field=models.CharField(choices=[('PVT', 'Privat'), ('OPN', 'Öppen')], default='OPN', help_text='Privat: endast administratörer kan se dina kontaktuppgifter. Öppen: andra inloggade kan se all din information. Inga personuppgifter kommer någonsin vara synliga för icke-inloggade. Medlemsnummer och namn kommer alltid vara synligt för inloggade.', max_length=3, verbose_name='sekretessnivå'),
        ),
    ]
