# Generated by Django 4.1.4 on 2022-12-22 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batadasen', '0014_person_email_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='tillställningens namn')),
                ('datetime', models.DateTimeField(verbose_name='tidpunkten för tillställningen')),
                ('signup_deadline', models.DateTimeField(verbose_name='sista anmälningsdag')),
                ('description', models.CharField(max_length=10000, verbose_name='beskrivning')),
                ('payment_instructions', models.CharField(max_length=10000, verbose_name='betalningsinstruktioner')),
                ('questions', models.JSONField()),
                ('administrators', models.ManyToManyField(related_name='event_administrators', to='batadasen.person')),
            ],
            options={
                'verbose_name': 'tillställning',
                'verbose_name_plural': 'tillställningar',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attenting', models.BooleanField(default=True, verbose_name='om personen avser närvara eller inte')),
                ('paid', models.BooleanField(default=False, verbose_name='om personen har betalt eller inte')),
                ('answers', models.JSONField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batadasen.event', verbose_name='event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batadasen.person', verbose_name='deltagare')),
            ],
            options={
                'verbose_name': 'eventanmälan',
                'verbose_name_plural': 'eventanmälningar',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(through='batadasen.EventRegistrations', to='batadasen.person'),
        ),
    ]
