# Generated by Django 4.1.4 on 2024-10-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batadasen', '0015_alter_person_options_alter_emaillist_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='medal_2',
            field=models.BooleanField(default=False, verbose_name='medalj 2'),
        ),
        migrations.AddField(
            model_name='person',
            name='medal_4',
            field=models.BooleanField(default=False, verbose_name='medalj 4'),
        ),
        migrations.AddField(
            model_name='person',
            name='medal_6',
            field=models.BooleanField(default=False, verbose_name='medalj 6'),
        ),
    ]
